version: '2.1'
services:
  oracle-db:
    hostname: oracle-db
    container_name: oracle-db
    image: container-registry.oracle.com/database/express:latest
    volumes:
      - ./config:/docker-entrypoint-initdb.d
      - ./sample-db:/sample-db
    healthcheck:
      test: [ "CMD", "/opt/oracle/checkDBStatus.sh"]
      interval: 2s
    environment:
      - ORACLE_SID=XE
      - ORACLE_PWD=mysecurepassword
      - ORACLE_CHARACTERSET=AL32UTF8
    ports:
      - "1521:1521"
      - "15080:8080"